### ISSUE TITLE
No exit key when seamap is opened

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#100]
If you walked to a ship to sail the seas and opened the seamap, there's oddly no exit key shown.

Most other windows do have an exit key displayed, so I suggest to show it for seamaps as well, just for consistency's sake.

**Comment by MaxMraz** [comment]
Turns out just the shop menus had the exit key displayed. I removed it from the shop menu for consistency, but added "exit" to the C key in the controls menu, since it's consistently the only way to exit all menus.
