### ISSUE TITLE
If you return to the temple at Spruce Head after you pushed the entrance button, the entrance button starts unpressed

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#103]
If you return to the temple at Spruce Head after you pushed the entrance button, the entrance button starts unpressed.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
This actually holds true for all floor switches in the game, they start maps un-depressed. I don't believe the engine stores the state of switches as pressed/not
