### ISSUE TITLE
Bear Warrior's Spear destroys plants only with low reach

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#106]
Bear Warrior's Spear destroys plants only when you're directly in front of them. Intentional?

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
This is actually something I dislike, but is an intentional decision of the engine. I discussed a possible idea of how to fix it with Christopho, but is lower-priority

**Comment by MaxMraz** [comment]
Actually, the only way to fix this would be if, in a future solarus update, a method is added like `destructible:cut()`. Without that, I wouldn't be able to add destroying-bushes behavior onto custom weapons.
