### ISSUE TITLE
Yarrowmouth: If you walk a 2nd time into the ambush cave (Nina) and defeat all monsters, then talk again to Nina, Nina will give you the quest again

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#107]
Yarrowmouth: If you walk a 2nd time into the ambush cave (Nina) and defeat all monsters, then talk again to Nina, Nina will give you the quest again.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
defeating the enemies always somehow set the quest back to the same phase

removed the enemies from the cave if you'd defeated them once
