### ISSUE TITLE
Quest "The Shoal Beast" can be repeated

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#109]
Quest "The Shoal Beast" can be repeate. How I did it:

- Defeat the beast BEFORE talking to the mayor
- Talk to the mayor, get reward
- Go back to beast, slay it again
- Message “Quest Updated” appears
- I got the same quest again and can claim my $$$ again

I did not test if it's possible to repeat the quest infinitely many times, or just once.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
you could do it forever lol
I set the monster as enabled(false) on map_started if you beat it already, but didn't remove the fact that the bait set it to enabled(true)

just fully removed() the monster and bait in map:on_started() when it's been previously defeated
