### ISSUE TITLE
10 arrow item gives 30 arrows

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#110]
I'm not sure, but I think if you walk over the item that says “10 arrows”, you get 30 arrows.

Tested in: 34a5e24

**Comment by Wuzzy2** [comment]
I have completed my first playthrough now, and it appears the “10 arrow item” only appears once in the entire game. Interesting. But I can't remember where I got it.

**Comment by MaxMraz** [comment]
Can't reproduce with the "10 arrow" item I have in the debug room- wondering if this is a weird hand-made item situation where it's not just a normal pickup.

Idk, if this just happened once though, I'll just keep an eye out for other reports, one pickup in the game that gives slightly more of a consumable isn't a big issue
