### ISSUE TITLE
Minor map design flaws

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#112]
1) At Yarrowmouth, the cliff renders above the tree:
https://satoshiupload.com/images/Xu7JVCSCKX.png

2) In the “forest temple” near Yarrowmouth, you can walk through the somehow. This looks odd:
https://satoshiupload.com/images/64SwL3IL4e.png

3) Silent Glade: Unreachable apple trees and berries:
https://satoshiupload.com/images/kJJDRmG17X.png
https://satoshiupload.com/images/0LOvPnYcDu.png

4) In some area that has “Stone” in the name (I forgot): The bottom left and bottom right pixels of this pirate house are transparent and you can see the water, so it looks like as if the house is floating:
https://satoshiupload.com/images/oxXjOPhmka.png

5) Pirate Vault: These stairs go upwards but they look like as if they go downwards:
https://satoshiupload.com/images/gofuZiZCbJ.png

Tested in: 34a5e24

**Comment by Wuzzy2** [comment]
6. There's no keyhole in the door to the wooden pirate fort North of Lotus Shoals; also no sound for opening it

**Comment by Wuzzy2** [comment]
I just realized that number 1 in my list is a duplicate of #83.

**Comment by Wuzzy2** [comment]
7. West of Limestone Island: There's a hidden beach cave with chests. If you walk up and left, you render in front of the stone
8. Zephyr Bay: Secret bombable entrance locks up again after re-entering screen: https://satoshiupload.com/images/kHTkpzpsfP.png
9. Ivystump: Hammer of hammer dude renders behind objects.
10. Gull Rock: If you walk behind the big tree, you appear in front of it: https://satoshiupload.com/images/EXBH9OjJOo.png
11. Sunken Palace: Many wall tiles are bad, because many pixels show the water through where no water should logically be seen: https://satoshiupload.com/images/YEhlWMFx0h.png
12. Sunken Palace: The yellow/white switch apparently does nothing

**Comment by Wuzzy2** [comment]
13. Lake Umber: Wall texture discontinuity. https://satoshiupload.com/images/v6iLpvbAc7.png
14. Oakhaven pub basement: When you walk through the secret passage, you can see Tilia's head (see right in the screenshot, the yellow stuff is Tilia's hair!). https://satoshiupload.com/images/YGRnOreaXi.png
15. Lake Umber: Sand texture discontinuity. https://satoshiupload.com/images/jug6dz8PvQ.png
16. Oakhaven: Green archway house (in front of the ghost house) has subtle texture discontinuity. https://satoshiupload.com/images/ApRR7A8Fgk.png
17. Oakhaven general store displays bombs before they sell any.
18. Oakhaven: If you buy bombs in the bomb store, you render behind the wood. https://satoshiupload.com/images/rb5gL43toT.png
19. Oakhaven Palace courtyard: You render above the balloons (the topmost balloons to the right)
20. Island of Storms: If you push the stone block upwards instead of left, you can't reach the chest. To reset this stone, you have to return all the way to the entrance and return. Annoying. In the screenshot it was done correctly, after the 2nd attempt. https://satoshiupload.com/images/2giZ30wPBS.png

**Comment by MaxMraz** [comment]
thanks for the catches! Fixed!
