### ISSUE TITLE
Issues with “falling down a floor” animation

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#115]
- When you fall down to the floor below, the "fall down" sound effect is not well-synced with the animation
- When you fall down to the floor below but push one of the walking keys, you basically skip the animation

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Hero was frozen in map:on_started(), which gets overwritten when map:on_transition_finished() is called, unfreezing the hero, allowing that movement while falling. I just set a 300ms timer to re-freeze the hero, basically, to stop any movement.

Also, delayed the "pweeeew" falling sound, and re-synched the landing sound.
