### ISSUE TITLE
Some bush slashing animations have leaf color mismatch

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#116]
If you destroy a bush by slashing it, you will see the leaves flying. For most bushes, the animation color matches the bush color.

However, there are some bushed in which there is a color mismatch.

For example, in Stonefell Crossroads. There are other bush types as well. Basically everything that is not using that lush green color.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Good observation, I shifted the hue so it is a bit more average between all bushes
