### ISSUE TITLE
If you collect an item in the top right corner, the "item collected" overlay hides the player

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#117]
If you collect a berry (or other item) while you are standing in the top right corner of the screen, the "item collected" overlay hides the player for a moment. It's just a minor annoyance, not even a real bug. Just saying.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Agreed, it's a bit annoying, but unfortunately something I'll let stay because there's only so much time in a life
