### ISSUE TITLE
Typo at Ivystump harbour

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#119]
At the harbour at Ivystump, Lily says: "I can't get enought"

Tested in: 34a5e24

**Comment by Wuzzy2** [comment]
More typos:

* In the apothecary in Oakhaven: "Oh! If you like to use the crafing table, feel free."
* Quest text for The Dog's Birthday quest: "The guard captains wants you to to find a (...)"

**Comment by MaxMraz** [comment]
Thanks, fixed these!
