### ISSUE TITLE
Crowfeather Boomerang wrong icon/name in inventory

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#122]
After you got the Crowfeather Boomerang, it is still called "Boomerang" in the inventory and has icon as old boomerang.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Unfortunately, the fact that the description and icon don't change when the item upgrades is actually a bugfix for a different bug. It's not worth rewriting the menu to fix the other bug to fix this one : (
