### ISSUE TITLE
[suggestion] Make bird shadow damagable by lightning charm

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#124]
This is a suggestion.
There is this enemy which I call “bird shadow”. It drops eggs on you.

I suggest to make it possible to attack the bird shadow with the lightning charm.

Downside: This might make lightning charm too overpowered? Gameplay-wise, the bird shadow is unique in that you can't kill it. This might be deliberate …
So I am not sure about my suggstion myself, but I thought I mention it because I though the idea sounds fun.

**Comment by MaxMraz** [comment]
zap zap

Added it in, I think it's an obscure enough idea that if a player thinks of that, they'll feel really clever if it works. And also it did't feel great that it _didn't_ work, because logically it makes sense.
