### ISSUE TITLE
Game freezes when you complete Seabird quest and return to the well near Goatshead.

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#125]
If you complete the Seabird quest, then return to the well near Goatshead and drink from it, there will be first a new dialogue. But when it finished, the game just freezes and you can't continue at all. You are forced to shutdown the game.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Forgot to unsummon heron after that particular dialog. Good catch!
