### ISSUE TITLE
Seabird seal at Smoldering Rock sometimes fails to get destroyed by Seabird's Tear

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#126]
The seabird seal at Smoldering Rock sometimes fails to get destroyed by Seabird's Tear. I have required multiple attempts to actually break the seal. I always stood directly in front of it …
Strange. All other seals broke after the first try.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
misc type enemies were still counting against the attack's total number of lightning bolts. So although lightning no longer targets misc-type enemies like projectiles, fire bursts (like those near this door), traps etc., these types of enemies, if counted before valid and target-able enemies, would remove from the total available lightning bolts for the attack.

I also moved the code that would open a Seabird sealed door to before the attack, so regardless of how many enemies were counted before it counted the door, the door will be opened.
