### ISSUE TITLE
Buying bombs in general stores doesn't work

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#127]
Buying bombs in general stores (after you have completed the bomb quest) doesn't work. If you try to buy a bomb, nothing happens.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Was pulling the item amount from the "bomb" item, which doesn't have an amount. Changed it so it pulls amount from the "bombs_counter_2" item which is the one it needs to be
