### ISSUE TITLE
Fort Crow boss fight restarts

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#129]
Fort Crow: If you beat the boss, then take the seamap, then go back in all the way to the boss room, the boss fight repeats.

(Note: I returned to the boss room because I didn't took the life bonus but the game kicked me out of the fort because I took the seamap first … -_-)

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Forgot to set a value to disable the sensor
