### ISSUE TITLE
Main menu music does not restart when returning to main menu

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#135]
How to reproduce:

* Start Ocean's Heart (main menu music should play)
* Start or load game
* Open your menu
* Select “Quit”
* You are now in the main menu

EXPECTED: Main menu music plays again
ACTUAL RESULT: No music plays

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Set the  `sol.audio.play_music()` function on a 100ms delay after the menu starts, seems to have fixed the issue.

Not sure about cause
