### ISSUE TITLE
Add readme and license

### ISSUE THREAD

**Issue by alexgleason** [MaxMraz/oceans-heart#17]
Including a readme and license will make the project more presentable and clear.

The ZSDX readme is a nice place to start for a readme: https://gitlab.com/solarus-games/zsdx/blob/dev/readme.md

For the license, you can make it as simple or complicated as you want. The simple way would be to say "everything is GPL." The complex way is to list every single file and include that file's license.

**Comment by Rampoina** [comment]
Very nice game!

The solarus [webpage](https://www.solarus-games.org/en/games/oceans-heart) lists your game as GPL v3 and CC-BY-SA 4.0.
Is this true? if so, could you add a LICENSE file?

**Comment by MaxMraz** [comment]
Added
