### ISSUE TITLE
Stairs not traversable in the center of them

### ISSUE THREAD

**Issue by Renkineko** [MaxMraz/oceans-heart#37]
Don't know if already reported, but the hero can't traverse some stairs if not longing the side, like here:

![2019-04-27 14-24-46 mp4](https://user-images.githubusercontent.com/2254151/56849737-97d4e200-68f8-11e9-8e63-0becedbad33e.gif)

(west of goatshed harbor)

**Comment by MaxMraz** [comment]
solved with complex multiple entity mess, ugh. but, solved
