### ISSUE TITLE
Too long text for dialog box

### ISSUE THREAD

**Issue by Renkineko** [MaxMraz/oceans-heart#38]
I know I already found one but can't remember where (definitely somewhere in goatshed harbour). Another one can be found in crakhood village:

![image](https://user-images.githubusercontent.com/2254151/56850917-39fcc600-6909-11e9-91ba-33de64457c65.png)

**Comment by Renkineko** [comment]
Elixer and Burlyblade Potion also have this problem.

**Comment by MaxMraz** [comment]
fixed in shop menu redo
