### ISSUE TITLE
Invisible wall

### ISSUE THREAD

**Issue by Rampoina** [MaxMraz/oceans-heart#80]
There's an invisible wall (in front of Tilia) just after the pirate is killed.
See the image for the location, I'll look up the name if needed.

![2020-02-16-185231_833x481_scrot](https://user-images.githubusercontent.com/5653911/74611364-63d2e380-50fb-11ea-9131-ebcf73b3b6d2.png)

**Comment by MaxMraz** [comment]
That's actually captain thyme's invisible body. Fixed
