### ISSUE TITLE
Sword swing animation renders behind objects

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#86]
The sword swing animation renders behind many (not all!) objects (e.g. stone, trees, etc.) depending on where you stand. It looks a little odd.

Tested in: 34a5e24307874b6b7ce25430853509504a92accd

**Comment by MaxMraz** [comment]
I agree, it does look a bit off. However, it's basically impossible to fix, and it so common throughout video games (you can often clip through walls with melee attacks in even AAA games), that I can't invest in addressing it
