### ISSUE TITLE
When using a berry, the LIFE and MAGIC bar flash

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#87]
When using a berry, the LIFE and MAGIC bar flash.

Tested in: 34a5e24307874b6b7ce25430853509504a92accd

**Comment by MaxMraz** [comment]
So the surfaces life and magic are drawn on, are recreated every time inventory:initialize is called (which it is every time you heal, to update inventory numbers and health/magic level).

Then, idk why, but I had a 100ms timer after the surface was recreated, before the stitches were drawn on it, causing this flash of time where the stitches weren't drawn. Not sure why I had that timer there. Took it out and fixed the flash.
