### ISSUE TITLE
Monster gets stuck in wooden barricade in 1st dungeon

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#88]
1st dungeon of Limestone Island: Creature can get stuck in the 2nd wooden blockade if closing the blockade at the right moment.

Push the button and wait until the monster is at the right spot, then walk off the button to make the barrier appear. The monster is now stuck.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
pretty rare that the monster would wander exactly over there, but added a wall to block it just the same
