### ISSUE TITLE
Weird dungeon reset in 1st dungeon

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#89]
In the 1st Dungeon of Limestone Island: If you open the 2nd wooden blockade by pushing a crate on th button, then leave the dungeon all the way back to the dungeon entrance, then go back inside, the blockade now starts opens, although no box is on it. If you walk on the button, the blockade re-appears.

This behavior is weirdly inconsistent.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Honestly, there was't a great reason to save that door state anyway, which is what causes this- the block gets reset but the door stays in its last state.
