### ISSUE TITLE
You won't fall on falling floor until you move

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#90]
In the 1st Dungeon on Limestone Island: If you walk on the falling floor and stand still, you won't fall until you walk.

Tested in: 34a5e24

**Comment by MaxMraz** [comment]
Oppa Wile E. Coyote style

This is a big weird, but will unfortunately take too many resources to fix something that isn't game-breaking, and the way this plays out in other instances is actually more in the player's favor. It's only in this one situation where you're forced to fall that it's noticable
