### ISSUE TITLE
Items don't appear in quest log

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#92]
On Goatshead Island, if you do the carrot mission and clear the monsters at the carrot boxes, you can look at the carrot barrel and take a carrot. However, those never appear in your inventory.
Although the game apparently keeps track of how many carrots I collected, it stops after collecting 2 carrots.

Is this intentional?

Tested in: 34a5e24

**Comment by Wuzzy2** [comment]
Some other items that neither appear in inventory nor quest log or anywhere else I looked:

- Master Armorer's Tools (Ballast Harbour)
- Tungsten Ore

**Comment by Wuzzy2** [comment]
More items:

* Poison Grove: Monk Plant (or whatever it's called)
* Key to Oakhaven (given to you by the mayor, probably not important)

**Comment by MaxMraz** [comment]
Other than the carrots (which are a one-off joke, I was implying Tilia eats them right there as a snack), these are all quest items and would appear in the quest log. I'll have to add them in to appear like the items in the log that currently do.

**Comment by MaxMraz** [comment]
Armorer tools are showing up for me?:
![image](https://user-images.githubusercontent.com/43142856/75635480-5ed65f80-5be4-11ea-8d98-3cbcff4a823f.png)

And Monkshood Petals:
![image](https://user-images.githubusercontent.com/43142856/75635821-23896000-5be7-11ea-9bf9-b18d6846dfd2.png)


Thanks for catching the Tungsten Ore, I forgot to add that one!

The key to oakhaven is just a joke. For now, at least. Maybe someday I'll add in a door that you need to use that to open
