### ISSUE TITLE
Invisible dialog options

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#93]
In some dialoguges in which u are asked a question, you can move the cursor to an invisible option.

Examples in Goatshead Island:

- Talking to Explorer in Inn
- Talking to Phantom Squid

Tested in: 34a5e24

**Comment by Wuzzy2** [comment]
Actually, this bug seems to happen with most multiple-choice dialogues. Only few exceptions seem to function correctly.

**Comment by MaxMraz** [comment]
Can't seem to reproduce this with the examples you're giving. Can you be more specific about which dialogs specifically you see this in? Not just who, but when exactly in the dialog, and which choice?

**Comment by Wuzzy2** [comment]
If you talk to the phantom squid after you catched it in that house (by talking to it), there appears a question at some time. Push up or down until the arrow is at an “impossible” position. There is only one multiple-choise question in this dialog, so you should be able to find it.

**Comment by MaxMraz** [comment]
![dialog-options](https://user-images.githubusercontent.com/43142856/75628321-bdc8b400-5ba5-11ea-9ec7-978698868616.gif)

I'm wondering, are you running a different version of Solarus? I'm on 1.6.2

**Comment by Wuzzy2** [comment]
1.6.0 here. Probably that's the reason? Too lazy to test right now.

Feel free to close.

**Comment by MaxMraz** [comment]
Must have been fixed in 1.6.1 or 1.6.2
