### ISSUE TITLE
Controls are not shown

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#94]
Most of the controls aren't shown, I can only guess them.

**Comment by MaxMraz** [comment]
It's designed more for a controller than a keyboard, where this wouldn't really be as much of an issue, but yeah. Added in some dialogs at the beginning to explain how to move, interact with objects, and open the menu.

**Comment by MaxMraz** [comment]
![image](https://user-images.githubusercontent.com/43142856/75642582-074aea80-5c0a-11ea-97d6-abe965bb2a11.png)

yeet
