### ISSUE TITLE
No text for lever

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/oceans-heart#96]
If you push space bar in front of a lever, nothing happens.

(I know you must use the sword, but maybe show some useful text when using spacebar?)

**Comment by MaxMraz** [comment]
This would actually require an engine change, as there's no event defined for this interaction. Might open an issue about it

**Comment by Wuzzy2** [comment]
Sure? In the LOZ clones on Solarus I repeatedly saw a dialog when I pushed spacebar in front of the yellow/white switch.

**Comment by MaxMraz** [comment]
Do you know which games? If so, I might be able to look into their code, but as far as scouring the Solarus docs, if I were to do this, it'd involve entirely re-implementing the switch as a custom entity, as far as I can tell. There doesn't seem to be an event that is called when the player presses the space bar in front of a switch. At least not that I can see a developer easily has access to.

**Comment by Wuzzy2** [comment]
ZSDX, for example.

At least for the blue/red crystal switches. I did not test the yellow/white switches, however.
